### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by francisbrito** [xrps/fcm-token-registry#1]
- [x] Add code coverage reports.
- [x] Add more storage providers (MongoDb, Redis, Postgres, ...)
- [x] Add API documentation. (pref Swagger/OpenAPI spec)
- [x] Add usage & examples.
- [ ] Add FCM project management endpoints.
- [ ] Add endpoints to emit notifications.
- [ ] Add pagination support.
